### ISSUE TITLE
Integrate with node's event loop

### ISSUE THREAD

**Issue by TooTallNate** [TooTallNate/NodObjC#2]
This is a tough one... But basically since node maintains it's own event loop, it makes it rather hard to make Objective-C's `NSRunLoop` or `CFRunLoop` integrate with it.

Currently, some code as simple as this will crash your terminal tab, since node repl runs in raw mode and we're subsequently starting a new event loop on the main thread, even Ctrl+C won't get you out:

``` javascript
var $ = require('NodObjC')
$.import('Foundation')
$.NSRunLoop('currentRunLoop')('run')
```

There is only one solution that I can think of: Write a Cocoa backend for libev (or libuv) so that it's underlying event loop *is* `NSRunLoop`. So far I have not looked into what that would entail, but I'm assuming it's not a trivial task...

Any additional insight on the subject would be appreciated in the meantime.

/cc @ry

**Comment by shanewholloway** [comment]
Some non-UI [NSMetadataSearch example code][1] leveraging the working event loop made possible by [pull request 56][2]. The example monkey patches in the absence of the pull request being applied.

[1]: https://gist.github.com/shanewholloway/161a4eaf46724eacc03b
[2]: https://github.com/TooTallNate/NodObjC/pull/56

**Comment by TooTallNate** [comment]
@shanewholloway Have you figured out a way to make this EventLoop class replace `app('run')`, i.e. in the `NodeCocoaHelloWorld.app` example app?

**Comment by shanewholloway** [comment]
Sure. [Updated pull request #56](https://github.com/shanewholloway/NodObjC/commit/73440e96828aaedf88b4e771db7afbfdff6d853a) with revised `NodeCocoaHelloWorld.app` example app powered by EventLoop module.

**Comment by TooTallNate** [comment]
Are you a god?

![](http://38.media.tumblr.com/77f674324a2ce0f0928e3f5edd3a3559/tumblr_nbr4r9RZ0M1qhds48o1_400.gif)

**Comment by shanewholloway** [comment]
Thanks for the high-praise! I've just been here before in a cross-platform C/C++ library with bindings for Node and Python. ;) Most of the work is in learning Node's `ffi`, `ref`, and `NodObjC` specifics. Happy to help out – the knowledge isn't doing anyone good stuck in my head! Can't wait to see what the community does with it.

**Comment by trevorlinton** [comment]
@shanewholloway VERY impressive. Your'e the type of guy who if he has a few hours of free time runs a 100 mile marathon, saves a bald eagle... from a shark.

Well done.

+1 for merge.

**Comment by TooTallNate** [comment]
@shanewholloway I'm curious as to why on your gist example, the "applicationDidFinishLaunching" callback never gets invoked. Any thoughts there?

**Comment by shanewholloway** [comment]
Apologies for the oversight. Forgot to add the call to `app('finishLaunching')` toward the end. [Revised by iPhone][a], so gist change not yet verified. See [other gist][b] I put together for question in pull request #56 that did work last night.

[a]: https://gist.github.com/shanewholloway/321aeb5f8467fbd459d2#file-cocoa-hello-world2-js-L51

[b]: https://gist.github.com/shanewholloway/c11a0180f780c16a3452#file-demo-applicationdidfinishlaunching-js-L27

**Comment by TooTallNate** [comment]
Closing. Thanks again @shanewholloway :)

**Comment by bernhard-42** [comment]
I played with Shane's gist of Jan 14, replaced setInterval by setTimeout to just verify that it works, but not add more load. I observed that helloworld2.js sitting there waiting consumes about 42% of my CPU (Core i7 mac mini) using the EventLoop appraoch.
Moving back to app('run') - obviously the timeout log does not appear any more - the CPU is more or less 0%
Is it expected that the integrated event loop is as "busy"?
The event loop integration works really well, but it seem quite expensive ...

**Comment by shanewholloway** [comment]
Yes, a CPU-intensive event loop is the expected behavior of this implementation example. The specific combination I put together for the sample is written to go "flat-out", running the Cocoa event loop non-blocking. This will return control of the process to NodeJS for additional javascript-land processing.

A real GUI app will want to tweak `untilDate` argument in [`eventLoopCore`](https://gist.github.com/shanewholloway/c11a0180f780c16a3452#file-eventloop-js-L99) to a date a little into the future so the process blocks politely in the Cocoa event loop, providing a responsive GUI. You can try this by setting the value to `$.NSDate('distantFuture')` – you should see your CPU utilization drop to low single digits. However, doing so will starve out the NodeJS event loop.

This balance is why I put EventLoop implementation forward as an example, but not yet as a package. The code is good enough, hopefully, to be forked and improved upon. But I wasn't able to put enough care and thought into the API to provide control over that balance yet. (That pesky day job…) And there are other concerns as well – for instance, I'd suggest looking into cluster module style forking approach to separate GUI and server processes.

**Comment by TooTallNate** [comment]
Ideally we would be able to have libuv poll the Cocoa event loop fd and be notified by a JavaScript event whenever there's Cocoa events to process. This would give the optimal CPU usage / responsiveness.

@shanewholloway Do you know if there's any possible way to poll the event loop file descriptor, or something equivalent to that?

**Comment by TooTallNate** [comment]
Possibly related: http://www.cocoabuilder.com/archive/cocoa/224547-questions-about-nsapplication-run.html#224616

> > If you can require Leopard, take a look at CFFileDescriptor.  Prior to
> > Leopard, you can use CFSocket with any file descriptor, so long as you don't
> > use the socket-specific parts of that interface.
>
> I do indeed require Leopard for other reasons (my Cocoa bridge uses
> the Objective C 2.0 runtime API) so that's not an issue. This should
> be an easy fix, since my non-blocking I/O code has pluggable backends;
> I can use the Core Foundation run loop on OS X and select() on other
> Unices. Looks I can solve the Exposé problem I mentioned in my
> original e-mail, as well as the pesky 1-3% CPU usage when idle, and
> get rid of some hackish code, in one fell swoop.

**Comment by shanewholloway** [comment]
@TooTallNate I do not know. I would suspect a collection of descriptors.

**Comment by bernhard-42** [comment]
@shanewholloway I played around with untilDate but did not find a great balance between CPU usage (let's say 1 digit percentage) and GUI responsiveness.
I like your idea about cluster module so I started looking into it. One problem is that server process and GUI process need to communicate. The first idea of using a rpc library like dnode does not work, since GUI process does not react on sockets driven by node eventloop.
Looks like one needs some rpc approach that leverages Cocoa for network connectivity in GUI process and can use some standard node stuff  in server process. Need to do some further research ...

**Comment by cztomsik** [comment]
I know this is old but for anyone else wondering how to integrate node/xxx event loop with cocoa:
- you need something like `setImmediate` to "tick" forever (in non-blocking way)
- you get next timeout/interval (`libuv_backend_timeout`)
- you wait for cocoa events with that timeout (block) like [this](https://github.com/glfw/glfw/blob/05dd2fa2986c37e7aee3cba917b1d02a3a189390/src/cocoa_window.m#L1432)
- you have a thread which will do `kevent(libuv_fd, null, empty_dest_kevent, 1, null)`
- and if it returns anything >0 you know there's a pending nodejs/libuv event (I/O is ready, etc.) so you need to wakeup cocoa (with glfw its `glfwPostEmptyEvent` and here's [how they do it](https://github.com/glfw/glfw/blob/05dd2fa2986c37e7aee3cba917b1d02a3a189390/src/cocoa_window.m#L1464))

It took me a while but it actually works perfectly and it has very low CPU overhead.

BTW: you need to call event handling from the main thread (that's why you need that `setImmediate` loop) - even if you've found a way to get events from other thread it could stop working in future and it wouldn't work on IOS anyway.
